### ISSUE TITLE
Home page issue

### ISSUE THREAD

**Issue by abhijha1** [ABES-CodeChef/CC-Website-5.O#23]
When redirecting to logo from any other page, logo disappears but comes to home1.html and after refreshing it comes back again

**Comment by SaiAryan1784** [comment]
ok, give me till monday.

**Comment by Abhinav-Vishwakarma** [comment]
Issue Resolved!
![Screenshot (107)](https://github.com/user-attachments/assets/a69eeba7-b54a-4b7d-bc86-c7cb8315ff04)
![Screenshot (108)](https://github.com/user-attachments/assets/48352c60-d45d-46f2-b840-ec5809c6ed97)
![Screenshot (109)](https://github.com/user-attachments/assets/289fbe03-12a1-4466-911e-8ced0599f9d8)
![Screenshot (110)](https://github.com/user-attachments/assets/55be30e7-9d0a-4832-9388-372e9538f37b)

https://github.com/user-attachments/assets/19546716-7b8c-4c6b-8630-b8cfbf36afe0
